//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTopItemLogic.WcfTopItemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopItem", Namespace="http://schemas.datacontract.org/2004/07/TopEntity")]
    [System.SerializableAttribute()]
    public partial class TopItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _ClickUrlField;
        
        private string _CommissionField;
        
        private string _CommissionNumField;
        
        private string _CommissionRateField;
        
        private string _CommissionVolumeField;
        
        private string _CouponEndTimeField;
        
        private string _CouponPriceField;
        
        private string _CouponRateField;
        
        private string _CouponStartTimeField;
        
        private string _ItemLocationField;
        
        private string _KeywordClickUrlField;
        
        private string _KeywordsField;
        
        private string _NickField;
        
        private long _NumIidField;
        
        private string _PicUrlField;
        
        private string _PriceField;
        
        private string _PromotionPriceField;
        
        private long _SellerCreditScoreField;
        
        private long _SellerIdField;
        
        private string _ShopClickUrlField;
        
        private string _ShopTypeField;
        
        private string _TaobaokeCatClickUrlField;
        
        private string _TitleField;
        
        private long _VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ClickUrl {
            get {
                return this._ClickUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._ClickUrlField, value) != true)) {
                    this._ClickUrlField = value;
                    this.RaisePropertyChanged("_ClickUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Commission {
            get {
                return this._CommissionField;
            }
            set {
                if ((object.ReferenceEquals(this._CommissionField, value) != true)) {
                    this._CommissionField = value;
                    this.RaisePropertyChanged("_Commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CommissionNum {
            get {
                return this._CommissionNumField;
            }
            set {
                if ((object.ReferenceEquals(this._CommissionNumField, value) != true)) {
                    this._CommissionNumField = value;
                    this.RaisePropertyChanged("_CommissionNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CommissionRate {
            get {
                return this._CommissionRateField;
            }
            set {
                if ((object.ReferenceEquals(this._CommissionRateField, value) != true)) {
                    this._CommissionRateField = value;
                    this.RaisePropertyChanged("_CommissionRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CommissionVolume {
            get {
                return this._CommissionVolumeField;
            }
            set {
                if ((object.ReferenceEquals(this._CommissionVolumeField, value) != true)) {
                    this._CommissionVolumeField = value;
                    this.RaisePropertyChanged("_CommissionVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouponEndTime {
            get {
                return this._CouponEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this._CouponEndTimeField, value) != true)) {
                    this._CouponEndTimeField = value;
                    this.RaisePropertyChanged("_CouponEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouponPrice {
            get {
                return this._CouponPriceField;
            }
            set {
                if ((object.ReferenceEquals(this._CouponPriceField, value) != true)) {
                    this._CouponPriceField = value;
                    this.RaisePropertyChanged("_CouponPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouponRate {
            get {
                return this._CouponRateField;
            }
            set {
                if ((object.ReferenceEquals(this._CouponRateField, value) != true)) {
                    this._CouponRateField = value;
                    this.RaisePropertyChanged("_CouponRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouponStartTime {
            get {
                return this._CouponStartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this._CouponStartTimeField, value) != true)) {
                    this._CouponStartTimeField = value;
                    this.RaisePropertyChanged("_CouponStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ItemLocation {
            get {
                return this._ItemLocationField;
            }
            set {
                if ((object.ReferenceEquals(this._ItemLocationField, value) != true)) {
                    this._ItemLocationField = value;
                    this.RaisePropertyChanged("_ItemLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _KeywordClickUrl {
            get {
                return this._KeywordClickUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._KeywordClickUrlField, value) != true)) {
                    this._KeywordClickUrlField = value;
                    this.RaisePropertyChanged("_KeywordClickUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Keywords {
            get {
                return this._KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this._KeywordsField, value) != true)) {
                    this._KeywordsField = value;
                    this.RaisePropertyChanged("_Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Nick {
            get {
                return this._NickField;
            }
            set {
                if ((object.ReferenceEquals(this._NickField, value) != true)) {
                    this._NickField = value;
                    this.RaisePropertyChanged("_Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _NumIid {
            get {
                return this._NumIidField;
            }
            set {
                if ((this._NumIidField.Equals(value) != true)) {
                    this._NumIidField = value;
                    this.RaisePropertyChanged("_NumIid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _PicUrl {
            get {
                return this._PicUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._PicUrlField, value) != true)) {
                    this._PicUrlField = value;
                    this.RaisePropertyChanged("_PicUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Price {
            get {
                return this._PriceField;
            }
            set {
                if ((object.ReferenceEquals(this._PriceField, value) != true)) {
                    this._PriceField = value;
                    this.RaisePropertyChanged("_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _PromotionPrice {
            get {
                return this._PromotionPriceField;
            }
            set {
                if ((object.ReferenceEquals(this._PromotionPriceField, value) != true)) {
                    this._PromotionPriceField = value;
                    this.RaisePropertyChanged("_PromotionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _SellerCreditScore {
            get {
                return this._SellerCreditScoreField;
            }
            set {
                if ((this._SellerCreditScoreField.Equals(value) != true)) {
                    this._SellerCreditScoreField = value;
                    this.RaisePropertyChanged("_SellerCreditScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _SellerId {
            get {
                return this._SellerIdField;
            }
            set {
                if ((this._SellerIdField.Equals(value) != true)) {
                    this._SellerIdField = value;
                    this.RaisePropertyChanged("_SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ShopClickUrl {
            get {
                return this._ShopClickUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._ShopClickUrlField, value) != true)) {
                    this._ShopClickUrlField = value;
                    this.RaisePropertyChanged("_ShopClickUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ShopType {
            get {
                return this._ShopTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._ShopTypeField, value) != true)) {
                    this._ShopTypeField = value;
                    this.RaisePropertyChanged("_ShopType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _TaobaokeCatClickUrl {
            get {
                return this._TaobaokeCatClickUrlField;
            }
            set {
                if ((object.ReferenceEquals(this._TaobaokeCatClickUrlField, value) != true)) {
                    this._TaobaokeCatClickUrlField = value;
                    this.RaisePropertyChanged("_TaobaokeCatClickUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Title {
            get {
                return this._TitleField;
            }
            set {
                if ((object.ReferenceEquals(this._TitleField, value) != true)) {
                    this._TitleField = value;
                    this.RaisePropertyChanged("_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _Volume {
            get {
                return this._VolumeField;
            }
            set {
                if ((this._VolumeField.Equals(value) != true)) {
                    this._VolumeField = value;
                    this.RaisePropertyChanged("_Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfTopItemService.ITopItemService")]
    public interface ITopItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopItemService/SaveTopItemList", ReplyAction="http://tempuri.org/ITopItemService/SaveTopItemListResponse")]
        void SaveTopItemList(GetTopItemLogic.WcfTopItemService.TopItem[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopItemServiceChannel : GetTopItemLogic.WcfTopItemService.ITopItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopItemServiceClient : System.ServiceModel.ClientBase<GetTopItemLogic.WcfTopItemService.ITopItemService>, GetTopItemLogic.WcfTopItemService.ITopItemService {
        
        public TopItemServiceClient() {
        }
        
        public TopItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveTopItemList(GetTopItemLogic.WcfTopItemService.TopItem[] items) {
            base.Channel.SaveTopItemList(items);
        }
    }
}
